SELECT * FROM T_POLICY TP 
INNER JOIN T_CLIENT TC ON TP.CLIENT_NUMBER = TC.CLIENT_NUMBER
WHERE TP.POLICY_SUBMIT_DATE > '1/5/2018' AND EXTRACT(MONTH FROM TC.BIRTHDATE) = 9;

SELECT * FROM T_POLICY TP 
INNER JOIN T_AGENT TA ON TP.AGENT_CODE = TA.AGENT_CODE
WHERE TP.POLICY_STATUS = 'INFORCE' AND TA.AGENT_OFFICE = 'JAKARTA';

UPDATE T_AGENT
SET BASIC_COMMISSION = (TP.COMMISSION / TP.PREMIUM) * 100
FROM T_POLICY TP
WHERE T_AGENT.AGENT_CODE = TP.AGENT_CODE;

UPDATE T_POLICY
SET POLICY_DUE_DATE = DATE_TRUNC('MONTH', POLICY_SUBMIT_DATE) + INTERVAL '30 days' - INTERVAL '1 day';


SELECT * FROM T_POLICY
WHERE PREMIUM * (1 - (DISCOUNT / 100)) < 1000000
ORDER BY PREMIUM * (1 - (DISCOUNT / 100));