CREATE TABLE T_POLICY (
	POLICY_NUMBER INTEGER,
	POLICY_SUBMIT_DATE DATE,
	PREMIUM MONEY,
	DISCOUNT INT,
	COMMISSION MONEY,
	CLIENT_NUMBER VARCHAR(25) UNIQUE,
	AGENT_CODE VARCHAR(25) UNIQUE,
	POLICY_STATUS VARCHAR(30),
	POLICY_DUE_DATE DATE,
	CONSTRAINT T_POLICY_PK PRIMARY KEY (POLICY_NUMBER, CLIENT_NUMBER, AGENT_CODE)
);

CREATE TABLE T_AGENT (
	AGENT_CODE VARCHAR(25),
	AGENT_NAME VARCHAR(55),
	AGENT_OFFICE VARCHAR(35),
	BASIC_COMMISSION MONEY,
	FOREIGN KEY (AGENT_CODE) REFERENCES T_POLICY (AGENT_CODE)
);

CREATE TABLE T_CLIENT (
	CLIENT_NUMBER VARCHAR(25),
	CLIENT_NAME VARCHAR(55),
	BIRTH_DATE DATE,
	FOREIGN KEY (CLIENT_NUMBER) REFERENCES T_POLICY (CLIENT_NUMBER)
);

SELECT * FROM T_POLICY;
SELECT * FROM T_AGENT;
SELECT * FROM T_CLIENT;

INSERT INTO T_POLICY (POLICY_NUMBER, POLICY_SUBMIT_DATE, PREMIUM, DISCOUNT, COMMISSION, CLIENT_NUMBER, AGENT_CODE, POLICY_STATUS, POLICY_DUE_DATE) VALUES 
(001, '2018-1-5', 18600000, 10, 930000, 'CL001', 'AG001', 'INFORCE', NULL),
(002, '2018-1-5', 2500000, 10, 125000, 'CL002', 'AG002', 'INFORCE', NULL),
(003, '2018-1-10', 2500000, 10, 125000, 'CL003', 'AG003', 'TERMINATE', NULL),
(004, '2018-1-25', 4000000, 10, 200000, 'CL004', 'AG004', 'PROPOSAL', NULL),
(005, '2018-1-25', 2625000, 10, 131250, 'CL005', 'AG005', 'PROPOSAL', NULL);

INSERT INTO T_AGENT (AGENT_CODE, AGENT_NAME, AGENT_OFFICE, BASIC_COMMISSION) VALUES
('AG001', 'LIDYA', 'JAKARTA', NULL),
('AG002', 'RUDI', 'BALI', NULL),
('AG003', 'DICKY', 'BALI', NULL),
('AG004', 'DAVID', 'SURABAYA', NULL),
('AG005', 'FARIZ', 'SURABAYA', NULL);

INSERT INTO T_CLIENT (CLIENT_NUMBER, CLIENT_NAME, BIRTH_DATE) VALUES
('CL001', 'WAYNE ROONEY', '1956-5-11'),
('CL002', 'RYAN GIGGS', '1972-9-3'),
('CL003', 'DAVID BECKHAM', '1985-9-3'),
('CL004', 'MICHAEL OWEN', '2012-9-3');

-- a. 
SELECT P.* 
FROM T_POLICY P
JOIN T_CLIENT C ON P.CLIENT_NUMBER = C.CLIENT_NUMBER
WHERE P.POLICY_SUBMIT_DATE > '2018-01-15' 
  AND EXTRACT(MONTH FROM C.BIRTH_DATE) = 9;
  
-- b. 
SELECT P.*
FROM T_POLICY P
JOIN T_AGENT A ON P.AGENT_CODE = A.AGENT_CODE
WHERE P.POLICY_STATUS = 'INFORCE' AND A.AGENT_OFFICE = 'JAKARTA';

-- c. 
UPDATE T_AGENT A
SET BASIC_COMMISSION = (P.COMMISSION / P.PREMIUM) * 100 :: MONEY
FROM T_POLICY P
WHERE A.AGENT_CODE = P.AGENT_CODE;

-- d. 
UPDATE T_POLICY
SET POLICY_DUE_DATE = DATE_TRUNC('MONTH', POLICY_SUBMIT_DATE) + INTERVAL '30 days' + INTERVAL '1 month' - INTERVAL '1 day'
WHERE POLICY_DUE_DATE IS NULL;

-- e. 
SELECT *
FROM T_POLICY
WHERE (CAST(PREMIUM AS NUMERIC) / CAST(DISCOUNT AS NUMERIC)) < 1000000
ORDER BY (CAST(PREMIUM AS NUMERIC) / CAST(DISCOUNT AS NUMERIC));



